name: Publish to PyPi
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/mattsollamatools/
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
      - name: Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: "./pyproject.toml"
          version-path: "project.version"
      # - run: 
      - run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.9
        
